# Generated by Django 5.2.16 on 2026-08-20 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="announcement",
            options={
                "ordering": ["-is_pinned", "-publish_date"],
                "verbose_name": "Оповещение",
                "verbose_name_plural": "Оповещения",
            },
        ),
        migrations.AddField(
            model_name="announcement",
            name="announcement_type",
            field=models.CharField(
                choices=[
                    ("URGENT", "🚨 Срочное происшествие"),
                    ("OFFICIAL", "📢 Официальное объявление"),
                ],
                default="OFFICIAL",
                max_length=20,
                verbose_name="Тип оповещения",
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="appearance",
            field=models.TextField(blank=True, verbose_name="Внешность и приметы"),
        ),
        migrations.AddField(
            model_name="announcement",
            name="child_age",
            field=models.CharField(blank=True, max_length=50, verbose_name="Возраст"),
        ),
        migrations.AddField(
            model_name="announcement",
            name="child_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Имя и фамилия"
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="clothing",
            field=models.TextField(blank=True, verbose_name="Одежда"),
        ),
        migrations.AddField(
            model_name="announcement",
            name="contact_phone",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Контактный телефон"
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="extra_info",
            field=models.TextField(
                blank=True, verbose_name="Дополнительная информация"
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="incident_time",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Дата и время происшествия"
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="location",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="Место происшествия / Где видели",
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="announcements",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="category",
            field=models.CharField(
                choices=[
                    ("MISSING_CHILD", "🚸 Пропал ребёнок"),
                    ("MISSING_PERSON", "🔍 Пропал человек"),
                    ("FIRE", "🔥 Пожар / задымление"),
                    ("ACCIDENT", "💥 Авария / ДТП"),
                    ("DANGER", "⚠️ Опасность для жителей"),
                    ("OTHER_URGENT", "🚨 Другое происшествие"),
                    ("ELECTRICITY", "⚡ Электричество"),
                    ("WATER", "💧 Водоснабжение"),
                    ("ROADS", "🚧 Дороги"),
                    ("UTILITIES", "🛠 Коммунальные работы"),
                    ("SCHEDULE", "🕒 Режим работы"),
                    ("EVENT", "🎉 Событие"),
                    ("IMPORTANT", "📢 Важное"),
                    ("EMERGENCY", "🚨 Экстренное"),
                ],
                default="IMPORTANT",
                max_length=30,
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="announcements/",
                verbose_name="Изображение / Фото",
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "На модерации"),
                    ("ACTIVE", "Активно"),
                    ("REJECTED", "Отклонено"),
                    ("ARCHIVED", "В архиве"),
                ],
                default="ACTIVE",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
