# Generated by Django 5.2.17 on 2026-09-05 13:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_pushsubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время прочтения')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='notifications.announcement', verbose_name='Оповещение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_reads', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отметка о прочтении',
                'verbose_name_plural': 'Отметки о прочтении',
                'ordering': ['-read_at'],
                'indexes': [models.Index(fields=['user', 'announcement'], name='notificatio_user_id_c21a54_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'announcement'), name='unique_user_announcement_read')],
            },
        ),
    ]
