# Generated by Django 5.2.16 on 2026-09-09 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_announcementread"),
        ("notifications", "0005_notificationpreference"),
    ]

    operations = []
