# Generated by Django 5.2.16 on 2026-09-14 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0006_merge_20260909_1927"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AnnouncementRead",
        ),
    ]
