# Generated by Django 5.2.16 on 2026-08-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rolerequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="rolerequest",
            name="organization_address",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Адрес организации"
            ),
        ),
        migrations.AddField(
            model_name="rolerequest",
            name="organization_category",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Категория организации",
            ),
        ),
        migrations.AddField(
            model_name="rolerequest",
            name="organization_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Описание организации"
            ),
        ),
        migrations.AddField(
            model_name="rolerequest",
            name="organization_name",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Название организации",
            ),
        ),
        migrations.AddField(
            model_name="rolerequest",
            name="organization_phone",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Телефон организации"
            ),
        ),
        migrations.AddField(
            model_name="rolerequest",
            name="organization_working_hours",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Режим работы"
            ),
        ),
    ]
