# Generated by Django 5.2.16 on 2026-08-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_rolerequest_organization_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rolerequest",
            name="master_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Описание услуг мастера"
            ),
        ),
        migrations.AddField(
            model_name="rolerequest",
            name="master_experience",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Опыт работы мастера"
            ),
        ),
        migrations.AddField(
            model_name="rolerequest",
            name="master_phone",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Телефон мастера"
            ),
        ),
        migrations.AddField(
            model_name="rolerequest",
            name="master_specialization",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Специализация мастера",
            ),
        ),
    ]
