# Generated by Django 5.2.16 on 2026-08-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DirectoryEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("emergency", "Экстренные службы"),
                            ("utilities", "Коммунальные службы"),
                            ("masters", "Мастера и специалисты"),
                            ("organizations", "Организации"),
                            ("shops", "Магазины"),
                            ("pharmacies", "Аптеки"),
                            ("schools", "Школы и детсады"),
                            ("hospitals", "Больницы и медучреждения"),
                            ("taxi", "Такси"),
                            ("cafe", "Кафе и еда"),
                            ("other", "Другое"),
                        ],
                        max_length=50,
                        verbose_name="Категория",
                    ),
                ),
                ("phone", models.CharField(max_length=32, verbose_name="Телефон")),
                (
                    "second_phone",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        null=True,
                        verbose_name="Дополнительный телефон",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Адрес"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "working_hours",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Режим работы",
                    ),
                ),
                ("priority", models.IntegerField(default=0, verbose_name="Приоритет")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Активно"), ("inactive", "Неактивно")],
                        default="active",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Запись справочника",
                "verbose_name_plural": "Справочник аула",
                "db_table": "directory_entry",
                "ordering": ["-priority", "name"],
            },
        ),
    ]
