# Generated by Django 5.2.16 on 2026-07-27 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="ads/photos/%Y/%m/", verbose_name="Фотография"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата загрузки"
                    ),
                ),
                (
                    "ad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="ads.ad",
                        verbose_name="Объявление",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фотография объявления",
                "verbose_name_plural": "Фотографии объявлений",
                "db_table": "ads_ad_image",
                "ordering": ["id"],
            },
        ),
    ]
