# Generated by Django 5.2.16 on 2026-09-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0003_ad_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="expire_date",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="Действует до"
            ),
        ),
        migrations.AlterField(
            model_name="ad",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FOOD", "Продукты"),
                    ("ANIMALS", "Животные"),
                    ("EQUIPMENT", "Техника"),
                    ("BUILDING", "Стройматериалы"),
                    ("CLOTHING", "Одежда"),
                    ("ELECTRONICS", "Электроника"),
                    ("OTHER", "Разное"),
                ],
                default="OTHER",
                max_length=30,
                null=True,
                verbose_name="Категория",
            ),
        ),
    ]
