# Generated by Django 5.2.16 on 2026-08-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "driver_name",
                    models.CharField(max_length=100, verbose_name="Имя водителя"),
                ),
                ("phone", models.CharField(max_length=30, verbose_name="Телефон")),
                (
                    "from_location",
                    models.CharField(max_length=100, verbose_name="Откуда"),
                ),
                ("to_location", models.CharField(max_length=100, verbose_name="Куда")),
                ("trip_date", models.DateField(verbose_name="Дата поездки")),
                (
                    "departure_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Время отправления"
                    ),
                ),
                (
                    "seats_available",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Количество свободных мест"
                    ),
                ),
                (
                    "price",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Стоимость (₸)"
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Активная"), ("ARCHIVED", "В архиве")],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Поездка",
                "verbose_name_plural": "Поездки",
                "ordering": ["-trip_date", "-created_at"],
            },
        ),
    ]
