# Generated by Django 5.2.16 on 2026-07-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="price",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Стоимость (₸)"
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="seats_available",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Количество свободных мест"
            ),
        ),
    ]
